src/Data/Domain/Entity/LogBook.php
<?php

declare(strict_types=1);

namespace App\Data\Domain\Entity;

use App\Shared\Domain\Aggregate\AggregateRoot;

class LogBook extends AggregateRoot
{
    private int $id;
    private string $action;
    private ?User $user;
    private ?string $object_type;
    private ?string $object_id;
    private ?\DateTime $occurredOn;
    private ?string $metadata;

    public function getId(): int
    {
        return $this->id;
    }

    public function getAction(): string
    {
        return $this->action;
    }

    public function setAction(string $action): void
    {
        $this->action = $action;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): void
    {
        $this->user = $user;
    }

    public function getObjectType(): ?string
    {
        return $this->object_type;
    }

    public function setObjectType(?string $object_type): void
    {
        $this->object_type = $object_type;
    }

    public function getObjectId(): ?string
    {
        return $this->object_id;
    }

    public function setObjectId(?string $object_id): void
    {
        $this->object_id = $object_id;
    }

    public function getOccurredOn(): ?\DateTime
    {
        return $this->occurredOn;
    }

    public function setOccurredOn(?\DateTime $occurredOn): void
    {
        $this->occurredOn = $occurredOn;
    }

    public function getMetadata(): ?string
    {
        return $this->metadata;
    }

    public function setMetadata(?string $metadata): void
    {
        $this->metadata = $metadata;
    }
}

src/Data/Domain/Entity/User.php
<?php

declare(strict_types=1);

namespace App\Data\Domain\Entity;

use App\Shared\Domain\Aggregate\AggregateRoot;
use App\Shared\Domain\ValueObject\EmailAddress;

class User extends AggregateRoot
{
    private int $id;
    private EmailAddress $email;

    public function getId(): int
    {
        return $this->id;
    }

    public function getEmail(): EmailAddress
    {
        return $this->email;
    }

    public function setEmail(EmailAddress $email): void
    {
        $this->email = $email;
    }
}

src/Data/Infrastructure/UI/Controller/HomeController.php
<?php

namespace App\Data\Infrastructure\UI\Controller;

use Symfony\Component\HttpFoundation\Response;
use Twig\Environment;

class HomeController
{
    public function __construct()
    {
    }

    public function index(Environment $twig): Response
    {
        return new Response(
            $twig->render(
                'pages/home.html.twig'
            )
        );
    }
}

src/Data/Infrastructure/UI/Controller/LogBook/LogBookListController.php
<?php

namespace App\Data\Infrastructure\UI\Controller\LogBook;

use App\Data\Application\ListLogBook\ListLogBookQuery;
use App\Data\Domain\Event\LogBook;
use App\Event\Domain\Bus\Query\QueryBus;
use App\Shared\Application\Paginator;
use Symfony\Component\HttpFoundation\Response;
use Twig\Environment;

class LogBookListController
{
    public function __construct(private readonly QueryBus $queryBus)
    {
    }

    public function index(Environment $twig): Response
    {
        /** @var Paginator<LogBook> $results */
        $results = $this->queryBus->ask(new ListLogBookQuery());

        return new Response(
            $twig->render(
                'pages/data/logbook/list.html.twig',
                [
                    'results' => $results
                ]
            )
        );
    }
}

templates/pages/data/logbook/list.html.twig
{% extends 'base.html.twig' %}

{% block title %}Data: Log Book{% endblock %}

{% block content %}

    <div class="text-gray-600 dark:text-gray-300">
        <div class="max-w-7xl mx-auto px-6 md:px-12 xl:px-6">
            <div class="mb-20 space-y-4 px-6 md:px-0">
                <h2 class="text-center text-2xl font-bold text-gray-800 dark:text-white md:text-4xl">
                    Data: Log Book
                </h2>
            </div>

            <div class="grid gap-8 md:grid-cols-2 lg:grid-cols-2">
                {% for item in results.results %}
                    <div class="aspect-auto p-8 border border-gray-100 rounded-3xl bg-white dark:bg-gray-800 dark:border-gray-700 shadow-2xl shadow-gray-600/10 dark:shadow-none">
                        <div class="flex gap-4">
                            <div>
                                <h6 class="text-lg font-medium text-gray-700 dark:text-white">{{ item.id }}</h6>
                            </div>
                        </div>
                        <p class="mt-8">
                            Action: {{ item.action }}<br/>
                            Object: {{ item.objectType }} -> {{ item.objectId }}<br/>
                            Metadata: {{ item.metadata }}<br/>
                            Created: {{ item.occurredOn.format('d/m/Y H:i:s') }}<br/>
                        </p>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}